### ISSUE TITLE
logger is not a function

### ISSUE THREAD

**Issue by Rezcue** [angryelectron/xbmq-js#23] opened 2021-03-08 22:26 UTC
hey its me again.

pi@BaPi:~ $ npm install xbmq
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

+ xbmq@2.0.6
added 123 packages from 90 contributors in 10.074s

5 packages are looking for funding
  run `npm fund` for details

pi@BaPi:~ $ cd /home/pi/node_modules/xbmq
pi@BaPi:~/node_modules/xbmq $ nano config.json.sample
pi@BaPi:~/node_modules/xbmq $ ./xbmq.js
logger is not a function
pi@BaPi:~/node_modules/xbmq $

some times i get 

pi@BaPi:~/node_modules/xbmq $ ./xbmq.js
Timeout waiting for XBee response.

is it me doing something wrong?

**Comment by abythell** [comment] 2021-03-09 01:24
I probably pushed that logger update a bit too recklessly.  Let me look into that some more.  

As for the timeout error, that's usually caused by having the wrong port name or baud rate, or not configuring API mode on the XBee.   Just guessing without more to go on.  What port, serial adapter, and XBee are you using?

**Comment by Rezcue** [comment] 2021-03-09 02:42
Adapter: ICQUANZX Bluetooth Bee XBee Adapter USB zum seriellen Port Arduino für Arduin XBee Adapter 
port is /dev/ttyUSB0 
XBee S2C 
i tried to switch the ports and looked via 	ls -la /dev/serial/by-id into them. APi mode is on 2 on both XBees.  Baudrate is 9600 .
I switched now to the xbee-node and xbee.api-nodes and it work justt fine in NodeRed. I can write, read, turn on some leds and stuff. 

And i noticed that if u run Xbee node with the RX and TX you cant run XBMQ at the same time. I did get timeouts all the time.

**Comment by abythell** [comment] 2021-03-09 17:08
The logger issue will be fixed (and verified this time!) in v2.0.7 which should be published shortly.

If you can communicate with your XBee network directly using node-red, that confirms your XBee and serial port setup, so that's good.  However, if both xbmq and node-red are trying to access the same XBee on the same serial port, of course you'll get timeouts because only one application can open the serial port at one time.

You can still use node-red with xbmq  - but you'd pub/sub MQTT messages to your broker (via mqtt node) instead of sending them out the serial port (via xbee-api).

**Closed** 2021-03-09 17:12 UTC
